openapi: 3.0.0
info:
  title: Sample API
  description: API for user registration and login
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /signup:
    post:
      summary: ユーザー登録
      description: ユーザーを登録するAPI。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "test@example.com"
                password:
                  type: string
                  example: "P@ssw0rd"
      responses:
        "200":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User registered successfully"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password"
  /signin:
    post:
      summary: ユーザーログイン
      description: 登録済みユーザーのログインを行うAPI。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "test@example.com"
                password:
                  type: string
                  example: "P@ssw0rd"
      responses:
        "200":
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User logged in successfully"
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password"
  /me:
    get:
      summary: 現在のユーザー情報を取得
      description: 認証されたユーザーの情報を取得するAPI。
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Current user information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: "crawd4274+test@gmail.com"
                  name:
                    type: string
                    example: "John Doe"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
