version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
      - 15675:15675
    restart: unless-stopped
    volumes:
      - ./config:/mosquitto/config
