name = "iot-system-api"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "SAMPLE_KV"
id = "a6b7214e46654126b148b4da9ef8ea8b"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "iot-system-api"
database_id = "2d8f9222-16f3-4a4e-a901-39edd7ddbca2"
migrations_dir = "drizzle/migrations"

# [ai]
# binding = "AI"